apiVersion: apps/v1
kind: Deployment
metadata:
  name: hoobank-webapp-deployment
spec:
  replicas: 6  # Number of desired replicas
  selector:
    matchLabels:
      app: hoobank-webapp
  template:
    metadata:
      labels:
        app: hoobank-webapp
    spec:
      containers:
      - name: hoobank-webapp
        image: yash5090/hoobank-webapp:latest
        ports:
        - containerPort: 3000
