apiVersion: batch/v1
kind: Job
metadata:
  name: hoobank-webapp-job
spec:
  template:
    spec:
      containers:
      - name: hoobank-webapp-job
        image: yash5090/hoobank-webapp:latest
        ports:
        - containerPort: 3000
      restartPolicy: OnFailure
