apiVersion: v1
kind: Service
metadata:
  name: hoobank-webapp-service
spec:
  selector:
    app: hoobank-webapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
