apiVersion: apps/v1
kind: Deployment
metadata:
  name: hoobank-webapp-deployment
spec:
  replicas: 6 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: hoobank-webapp
  template:
    metadata:
      labels:
        app: hoobank-webapp
    spec:
      containers:
        - name: hoobank-webapp
          image: yash5090/hoobank-webapp:latest # Replace with the actual image tag
          ports:
            - containerPort: 3000 # Replace with the port your Tetris game listens on
